function ListCompartments = GetMetLocation(LmComp, PairedCompartments, UnpairedCompartments)
%% ========================================================================
% The 'GetMetLocation' function retrieves the compartment abbreviation of
% the LipidModule metabolite after the harmonization of compartment
% abbreviations between the models is carried out.
%
% USAGE:
%   ListCompartments = GetMetLocation(LmComp, PairedCompartments, UnpairedCompartments)
%
% INPUTS:
%   PairedCompartments:   List of compartments from LipidModule paired-up
%                         with the ModelTemplate compartments.
%
%   UnpairedCompartments: List of compartments of LipidModule which don't
%                         have a equivalent compartment in
%                         ModelTemplate.PairedCompartments.
%
% OUTPUTS:
%   ListCompartments:     List with compartment abbreviation of the
%                         LipidModule metabolite after the harmonization of
%                         compartment abbreviations between the models.
% =========================================================================
%%
pathHComps = fullfile('OutputFiles','HarmonizedComp.mat');
Temp1 = load(pathHComps); %Generated by the matlab app
HarmonizedComp = Temp1.harmonizedComp;

pathCommonComps = fullfile('OutputFiles','CommonComps.mat');
Temp2 = load(pathCommonComps);
CommonComps = Temp2.commonComps;

% Initialize variables:
IsCompartment = zeros(4,1);

% Compartment of LipidModule metabolite was harmonized:
GetCompIdx1 = strcmp(HarmonizedComp(:,2),LmComp);
IsCompartment(1) = sum(GetCompIdx1);

% Compartment of LipidModule metabolite was paired-up to equivalent
% comapartment in ModelTemplate:
GetCompIdx2 = strcmp(PairedCompartments(:,2),LmComp);
IsCompartment(2) = sum(GetCompIdx2);

% Compartment of LipidModule metabolite was not paired
GetCompIdx3 = strcmp(UnpairedCompartments(:,2),LmComp);
IsCompartment(3) = sum(GetCompIdx3);

% Compartment of LipidModule metabolite was already in ModelTemplate with
% same abbreviation:
GetCompIdx4 = strcmp(CommonComps(:,2),LmComp);
IsCompartment(4) = sum(GetCompIdx4);

% Find out current abbreviation of LipidModule metabolite:
AbbIndex = find(IsCompartment == 1);

switch AbbIndex
    case 1
        ListCompartments = HarmonizedComp(GetCompIdx1, 3);
    
    case 2
        ListCompartments = PairedCompartments(GetCompIdx2, 3);
    
    case 3
        ListCompartments = UnpairedCompartments(GetCompIdx3, 1);
    
    case 4
        ListCompartments = CommonComps(GetCompIdx4, 1);
end
    
% Harmonize brackets usage:
ListCompartments = strrep(string(ListCompartments),'[', '');
ListCompartments = strrep(ListCompartments,']', '');
ListCompartments = cellstr(strcat('[',ListCompartments,']'));

end